axonivy/dev-workflow-ui

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestSignalsIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/ViewerUtil.java

Workaround for now. Tried to do it more elegantly but I might need some more input from the others.

XIVY-9550 Fix NPE when a case was started by a signal

---

maven/config/pom.xml

Raising project-build-plugin version to 10.0.0 / 10.0.1-SNAPSHOT

Raising project-build-plugin version to 10.0.0 / 10.0.1-SNAPSHOT

---

maven/config/pom.xml

Reverts axonivy/dev-workflow-ui#117

Revert "Bump web-tester from 9.4.1 to 10.0.0"

---

maven/config/pom.xml

Raising web-tester version to 10.0.0

Raising web-tester version to 10.0.0

---

dev-workflow-ui-test-data/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui-test-data/processes/EngineMode.p.json
dev-workflow-ui-test-data/processes/NotEmbedInFrame.p.json
dev-workflow-ui-test-data/processes/TestData.p.json
dev-workflow-ui-test-data/processes/TestService.p.json
dev-workflow-ui-test-data/processes/TestViewPermission.p.json
dev-workflow-ui-test-data/processes/makeAdminUser.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TestDefaultPage/TestDefaultPageProcess.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TestDialog1/TestDialog1Process.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TestDialog2/TestDialog2Process.p.json
dev-workflow-ui/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui/processes/Main.p.json

Raise ivy projects to latest version

Raise ivy projects to latest version

---

dev-workflow-ui-test-data/pom.xml
dev-workflow-ui-test/pom.xml
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui/pom.xml
maven/config/iar/pom.xml
maven/config/pom.xml
maven/config/test/pom.xml
maven/deploy/pom.xml
maven/dev-workflow-ui-jar/pom.xml
maven/dev-workflow-ui-screenshots/pom.xml
maven/image-validation/pom.xml
pom.xml

Raise version to 11.1.0-SNAPSHOT

Raise version to 11.1.0-SNAPSHOT

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java

I think it is not completely fixed but better ...

Fix flaky process viewer test

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDownloadCaseDocumentsIT.java

Still not perfect, but there is no NPE in the Selenide Code now.

Fix flaky WebTestDownloadCaseDocumentsIT

---

dev-workflow-ui-test/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui-web-test/.settings/ch.ivyteam.ivy.designer.prefs

For some reason automatic update missed those 2 🤔

Raise missed IvyProjectVersion

---

Jenkinsfile
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDownloadCaseDocumentsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java

Im not sure how effective this will be. Cherry-picked the changes of christian from master + added some improvements I've noticed like improved scroll and small sleep. Also cleanup better after download tests now (I think this was the cause of flaky GLSP tests)

Improve flaky tests

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDownloadCaseDocumentsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java

Seems to be working pretty good
The same was merged to `release10.0`

Fix GLSP test and improve download test flakiness

---

dev-workflow-ui/webContent/view/frame.xhtml

XIVY-9722 Refresh iframe only refreshes the dialog and not the process

---

maven/config/pom.xml

Raising project-build-plugin version to 10.0.0 / 11.1.0-SNAPSHOT

Raising project-build-plugin version to 10.0.0 / 11.1.0-SNAPSHOT

---

Jenkinsfile
maven/deploy/pom.xml

Just need to wait untill `100.demo.ivyteam.io` is available 😄

Deploy release10 to 10.demo.ivyteam.io

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/startsPanel.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/resources/components/caseLink.xhtml
dev-workflow-ui/webContent/resources/components/startsPanelElement.xhtml
dev-workflow-ui/webContent/resources/components/taskLink.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/home.xhtml

Improve starts style

---

dev-workflow-ui/webContent/view/frame.xhtml

XIVY-9861 Fix white iframe flicker on dark mode

---

dev-workflow-ui/webContent/view/frame.xhtml

Fix white flicker in iframe and dark mode on

---

dev-workflow-ui/src/ch/ivyteam/workflowui/AdminIvyDevWfBean.java

This code is used nowhere, right?

XIVY-10146 Fix warning by removing all unused code in AdminIvyDevWfBean

---

dev-workflow-ui/src/ch/ivyteam/workflowui/starts/CustomPMV.java

Before it was called one time for the process starts and one time for the casemap starts

XIVY-10196 Only call getStartables() once per starts page

---

dev-workflow-ui/src/ch/ivyteam/workflowui/starts/CustomPMV.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/StartsDataModel.java

XIVY-10307 Dont call wpmv.getStartables() every time a filter changes >> R10

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseDetailsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseMapIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskLinkModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/webContent/includes/components/allTasksTable.xhtml
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/caseDetails/taskList.xhtml
dev-workflow-ui/webContent/includes/components/casesTable.xhtml
dev-workflow-ui/webContent/includes/components/personalTasksTable.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/resources/components/caseLink.xhtml
dev-workflow-ui/webContent/resources/components/taskLink.xhtml

XIVY-10312 Use business states of task and cases

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseDetailsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseMapIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskLinkModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/TaskUtil.java
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/casesTable.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/resources/components/caseLink.xhtml

XIVY-10312 Show technical state together with state instead of separete

---

dev-workflow-ui/webContent/view/login.xhtml

Favicon on login page should also use branding favicon as the other

Fix favicon on login page

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/PersonalTasksIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/UserUtil.java
dev-workflow-ui/webContent/includes/components/personalTasksTable.xhtml
dev-workflow-ui/webContent/resources/components/startsPanelElement.xhtml
dev-workflow-ui/webContent/view/caseDetails.xhtml
dev-workflow-ui/webContent/view/home.xhtml

Fix show other task states on filter:
Fix show tasks for other users:

XIVY-11208 Fix task search

---

dev-workflow-ui-test-data/processes/TestData.p.json
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomeRedirect.java
dev-workflow-ui/webContent/view/home.xhtml

- Fix use personalTasksIvyDevWfBean on home.xhtml
- Fix flaky WebTestHomeRedirect test
- Cleanup ivy session attribute first
- Run test before other tests

XIVY-11208 Fix home task list

---

dev-workflow-ui-test-data/processes/TestData.p.json
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomeRedirect.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/PersonalTasksIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/UserUtil.java
dev-workflow-ui/webContent/includes/components/personalTasksTable.xhtml
dev-workflow-ui/webContent/resources/components/startsPanelElement.xhtml
dev-workflow-ui/webContent/view/caseDetails.xhtml
dev-workflow-ui/webContent/view/home.xhtml

- Tasks: Don't show other states when filtering
- General: Don't show tasks which are not for the current user
- Don't do some page link check for taskmodel generation
Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/198
Fix flaky WebTestHomeRedirect test
- Cleanup ivy session attribute first
- Run test before other tests
Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/201

XIVY-11208 Fix task search > R10

---

maven/config/pom.xml

Raising web-tester version to 11.1.0

Raising web-tester version to 11.1.0

---

maven/config/pom.xml

Raising project-build-plugin version to 11.1.0 / 11.2.0-SNAPSHOT

Raising project-build-plugin version to 11.1.0 / 11.2.0-SNAPSHOT

---

dev-workflow-ui-web-test/pom.xml
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebDocuScreenshots.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseMapIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCleanup.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomeRedirect.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestIntermediateEventsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestSignalsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/util/WorkflowUiUtil.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java
dev-workflow-ui/webContent/includes/template/template.xhtml

Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/206

XIVY-11246 Fix npe after user switch if orignal url is case/task detail > R10

---

dev-workflow-ui-web-test/pom.xml

Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/212

Fix workflow jar dir on engine in pom > R11.1

---

dev-workflow-ui-test-data/pom.xml
dev-workflow-ui-test/pom.xml
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui/pom.xml
maven/config/iar/pom.xml
maven/config/pom.xml
maven/config/test/pom.xml
maven/deploy/pom.xml
maven/dev-workflow-ui-screenshots/pom.xml
maven/image-validation/pom.xml
pom.xml

Raise version to 11.2.0-SNAPSHOT

Raise version to 11.2.0-SNAPSHOT

---

maven/config/pom.xml

Raising project-build-plugin version to 11.1.0 / 11.1.1-SNAPSHOT

Raising project-build-plugin version to 11.1.0 / 11.1.1-SNAPSHOT

---

maven/config/pom.xml

Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDownloadCaseDocumentsIT.java

XIVY-10334 Disable download test >> R11.1

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDownloadCaseDocumentsIT.java

XIVY-10334 Disable download test >> R10

---

dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java

Will also merge to 11.1 and 10.0

XIVY-11342 Show error message if license sessions are exceeded

---

dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/resources/components/customFields.xhtml
dev-workflow-ui/webContent/view/profile.xhtml

Use <p:tooltip> tag instead of default HTML "title" attribute

---

dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/profile.xhtml

Improve profile layout

---

dev-workflow-ui/src/ch/ivyteam/workflowui/notification/NotificationBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/notification/NotificationDto.java
dev-workflow-ui/webContent/includes/template/notifications.xhtml
dev-workflow-ui/webContent/includes/template/sidebar.xhtml
dev-workflow-ui/webContent/includes/template/template.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css

- Simple implementation
- I want to implement lazy-loading endless scrolling later
- I will add tests at the end of the story

XIVY-11638 Add notification widget

---

.project
dev-workflow-ui/webContent/includes/template/template.xhtml
dev-workflow-ui/webContent/resources/js/vscodeConnection.js

Connection for https://github.com/axonivy/vscode-extensions/pull/102

XIVY-12427 Add vscode connection

---

dev-workflow-ui/webContent/resources/js/vscodeConnection.js

@ivy-lmu I think this got missed in my last pr 🙈

Fix postmessage on parent

---

maven/config/pom.xml

Raising web-tester version to 11.2.0

Raising web-tester version to 11.2.0

---

maven/config/pom.xml

Raising web-tester version to 11.2.1

Raising web-tester version to 11.2.1

---

maven/config/pom.xml

Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT

Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT

---

maven/config/pom.xml

Raising web-tester version to 11.3.0-SNAPSHOT

Raising web-tester version to 11.3.0-SNAPSHOT

---

dev-workflow-ui-test-data/pom.xml
dev-workflow-ui-test/pom.xml
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui/pom.xml
maven/config/iar/pom.xml
maven/config/pom.xml
maven/config/test/pom.xml
maven/deploy/pom.xml
maven/dev-workflow-ui-screenshots/pom.xml
maven/image-validation/pom.xml
pom.xml

Raise version to 11.2.1

---

dev-workflow-ui-test-data/pom.xml
dev-workflow-ui-test/pom.xml
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui/pom.xml
maven/config/iar/pom.xml
maven/config/pom.xml
maven/config/test/pom.xml
maven/deploy/pom.xml
maven/dev-workflow-ui-screenshots/pom.xml
maven/image-validation/pom.xml
pom.xml

Raise version to 11.2.1-SNAPSHOT

Raise version to 11.2.1-SNAPSHOT

---

dev-workflow-ui/webContent/view/frame.xhtml

XIVY-13226 undo visibility setting as it leads to other flickering

---

dev-workflow-ui-test-data/pom.xml
dev-workflow-ui-test/pom.xml
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui/pom.xml
maven/config/iar/pom.xml
maven/config/pom.xml
maven/config/test/pom.xml
maven/deploy/pom.xml
maven/dev-workflow-ui-screenshots/pom.xml
maven/image-validation/pom.xml
pom.xml

Raise version to 11.2.2-SNAPSHOT

Raise version to 11.2.2-SNAPSHOT

---

dev-workflow-ui/webContent/includes/template/notifications.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css

XIVY-13150 keep mark-as-read column even if read

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java

Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/345

XIVY-14082 Fix cases table leaks all cases if start filtering > R10

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java

XIVY-14082 Fix cases table leaks all cases if start filtering

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java

Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/345

XIVY-14082 Fix cases table leaks all cases if start filtering > R11.3

---

dev-workflow-ui/src/ch/ivyteam/workflowui/DateTimeIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/DateUtil.java
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/descriptionCardHeaderActions.xhtml
dev-workflow-ui/webContent/resources/components/datetime.xhtml
dev-workflow-ui/webContent/resources/components/workflowEventsTable.xhtml
dev-workflow-ui/webContent/view/task.xhtml

Cleanup details pages

---

dev-workflow-ui-test-data/processes/TestData.p.json
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/DateTimeIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/notes/NotesBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDetailsIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/DateUtil.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/TaskUtil.java
dev-workflow-ui/webContent/includes/components/taskDetails/descriptionCardHeaderActions.xhtml
dev-workflow-ui/webContent/view/notesDialog.xhtml

Simple field showing the count of notes and opening a dialog with the notes when clicked.
Do we also want to show notes for cases?
And should I also add the possibility to add notes or only read?

Add notes to task details

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebDocuScreenshots.java
dev-workflow-ui/src/ch/ivyteam/workflowui/StatisticsBean.java
dev-workflow-ui/webContent/includes/components/statistics/caseStateGraph.xhtml
dev-workflow-ui/webContent/includes/components/statistics/caseStatisticsChart.xhtml
dev-workflow-ui/webContent/includes/components/statistics/caseTopCreators.xhtml
dev-workflow-ui/webContent/includes/components/statistics/casesAll.xhtml
dev-workflow-ui/webContent/includes/components/statistics/taskStateGraph.xhtml
dev-workflow-ui/webContent/includes/components/statistics/taskStatisticsChart.xhtml
dev-workflow-ui/webContent/includes/components/statistics/taskTopWorkers.xhtml
dev-workflow-ui/webContent/includes/components/statistics/tasksAll.xhtml
dev-workflow-ui/webContent/includes/template/sidebar.xhtml
dev-workflow-ui/webContent/includes/template/statisticsCard.xhtml
dev-workflow-ui/webContent/includes/template/statisticsCardBare.xhtml
dev-workflow-ui/webContent/view/statistics.xhtml

I feel like theres something missing and I'm not sure what kinds of statistics to show. Are some of the current ones not worth showing and show something else instead? For now I looked a bit at what statistics portal is showing and some of my thoughts. Please leave feedback 😃

XIVY-14657 Statistics page

---

dev-workflow-ui/webContent/includes/components/taskDetails/descriptionCardHeaderActions.xhtml
dev-workflow-ui/webContent/view/case.xhtml

Just a quick improvement to instantly show the notes count on the notes buttons

XIVY-14659 Add badge with count on notes buttons

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java

Quick fix of the task and case models

XIVY-14658 Improve how row data is acquired on lazy tables with selection

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/StartedCasesDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/homepage/HomepageIvyDevWfBean.java
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/home.xhtml

XIVY-14658 Homepage adjustments

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCasesIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCleanup.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDefaultPagesIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProcessViewerPermissionIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProfileIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestSignalsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/StartsDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/ProcessModelsUtil.java
dev-workflow-ui/src/ch/ivyteam/workflowui/webservices/WebServicesBean.java
dev-workflow-ui/webContent/includes/components/casesTable.xhtml
dev-workflow-ui/webContent/includes/components/startsPanel.xhtml
dev-workflow-ui/webContent/includes/components/tasksTable.xhtml
dev-workflow-ui/webContent/includes/components/userTable.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/loginTable.xhtml
dev-workflow-ui/webContent/view/starts.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml
dev-workflow-ui/webContent/view/webservices.xhtml

To make it match the new processes page

XIVY-14720 Streamline more table search inputs

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestGLSPProcessViewerIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestSignalsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui/webContent/includes/components/caseDetails/taskList.xhtml
dev-workflow-ui/webContent/includes/components/signals/boundarySignals.xhtml
dev-workflow-ui/webContent/includes/components/signals/firedSignals.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/includes/template/sidebar.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/api-browser.xhtml
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/cleanup.xhtml
dev-workflow-ui/webContent/view/home.xhtml
dev-workflow-ui/webContent/view/intermediateEventDetails.xhtml
dev-workflow-ui/webContent/view/intermediateEvents.xhtml
dev-workflow-ui/webContent/view/loginTable.xhtml
dev-workflow-ui/webContent/view/profile.xhtml
dev-workflow-ui/webContent/view/signals.xhtml
dev-workflow-ui/webContent/view/starts.xhtml
dev-workflow-ui/webContent/view/statistics.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml
dev-workflow-ui/webContent/view/webservices.xhtml

- Streamline titles to all use same size (h4)
- Remove icons from titles
- Remove meaningless first column icon from tables
- CSS changes

XIVY-14720 Adjust styling

---

dev-workflow-ui/src/ch/ivyteam/workflowui/homepage/HomepageIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
dev-workflow-ui/webContent/view/home.xhtml

- Remove doubled preRenderView redirect
- Use the correct tasks model for open tasks

XIVY-14658 Fix homepage

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseDetailsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseMapIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDefaultPagesIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTaskDetailPageRedirectIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/state/StateBadgeBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/state/StateBadgeModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskLinkModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/TaskUtil.java
dev-workflow-ui/webContent/includes/components/caseDetails/caseList.xhtml
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/caseDetails/taskList.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/descriptionCardHeaderActions.xhtml
dev-workflow-ui/webContent/resources/components/caseLink.xhtml
dev-workflow-ui/webContent/resources/components/stateBadge.xhtml
dev-workflow-ui/webContent/resources/components/taskLink.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/home.xhtml
dev-workflow-ui/webContent/view/starts.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml
dev-workflow-ui/webContent/view/webservices.xhtml

XIVY-14720 Add case/task state badge

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui/webContent/includes/template/sidebar.xhtml
dev-workflow-ui/webContent/includes/template/template.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css

XIVY-14720 Adjust navigation header looks

---

dev-workflow-ui/webContent/view/home.xhtml

After removing the start time column it got wider

XIVY-14720 Adjust width of homepage task prio column

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebDocuScreenshots.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseDetailsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseMapIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProcessViewerPermissionIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDetailsIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/homepage/HomepageIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/TaskUtil.java
dev-workflow-ui/webContent/includes/components/caseDetails/taskList.xhtml
dev-workflow-ui/webContent/includes/template/template.xhtml
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/case.xhtml
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/home.xhtml
dev-workflow-ui/webContent/view/starts.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml

\+ change text color to normal from blue (like on Figma)
\+ added rerun button on case details

XIVY-14720 Use 3-dots on tables

---

build/Jenkinsfile
build/build.groovy
build/integration/Jenkinsfile
build/screenshots/Jenkinsfile
dev-workflow-ui-test-data/.settings/org.eclipse.core.resources.prefs
dev-workflow-ui-test/.settings/org.eclipse.core.resources.prefs
dev-workflow-ui-test/pom.xml
dev-workflow-ui-web-test/.settings/org.eclipse.core.resources.prefs
dev-workflow-ui-web-test/pom.xml
dev-workflow-ui/.settings/org.eclipse.core.resources.prefs
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/PersonalTasksDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
maven/config/pom.xml
maven/config/test/pom.xml
maven/deploy/pom.xml
maven/dev-workflow-ui-screenshots/pom.xml
maven/image-validation/pom.xml

- default: editor config check, build, deploy to nexus, JUnit tests, deploy to nightly demo engine
- integration: web tests (as iar project and as integrated jar)
- screenshots: screenshots, compare

Split pipelines

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java

sort state after businessState

XIVY-14845 Fix sort state in tasks and cases table after businessState

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java

- Filter for task and case business state
- Filter for task and case activator/creator display name

XIVY-14845 Fix task and case filters (business state, activator, creator)

---

dev-workflow-ui/webContent/view/home.xhtml

Otherwise I cannot click e.g. on the red spot, only the text and a short border above and below the red spot works to start the process.

Fix last starts

---

dev-workflow-ui-test-data/processes/TestData.p.json
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/ProcessByUrlBean.java

https://1ivy.atlassian.net/browse/XIVY-15030

XIVY-15030 fix hidden startEvent isnt startable

---

dev-workflow-ui/webContent/view/home.xhtml

Streamline home page for empty cards

---

dev-workflow-ui/webContent/includes/components/statistics/caseStateGraph.xhtml
dev-workflow-ui/webContent/includes/components/statistics/taskStateGraph.xhtml
dev-workflow-ui/webContent/view/webservices.xhtml

**statisic view with data**
before:
after:
**webservice table icon column**
before:
after:

Small ui fixes

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProcessViewerPermissionIT.java

Test didn't appear in 10 runs, so hopefully improved...

Stabilize WebTestProcessViewerPermissionIT tests

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CaseModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDetailsIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/state/StateBadgeBean.java
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml

XIVY-15985 Show all case owners on case details

---

dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java
dev-workflow-ui/webContent/view/loginTable.xhtml

master: https://github.com/axonivy/dev-workflow-ui/pull/526

XIVY-15992 Block loginTable if not dev or demo mode > R12

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CaseModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDetailsIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/state/StateBadgeBean.java
dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml

master: https://github.com/axonivy/dev-workflow-ui/pull/527

XIVY-15985 Show all case owners on case details > R12

---

dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java
dev-workflow-ui/webContent/view/loginTable.xhtml

master: https://github.com/axonivy/dev-workflow-ui/pull/526

XIVY-15992 Block loginTable if not dev or demo mode > R10

---

build/build.groovy
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginTableIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java

core: https://github.com/axonivy/core/pull/7817
- loginTable only login to test users + if the password is equal to the username
- only list test users

XIVY-15954 Login table should only login marked users per default

---

build/build.groovy
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginTableIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java

https://github.com/axonivy/dev-workflow-ui/pull/533

XIVY-15954 Login table should only login marked users per default > R12

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/test/ProxyExtension.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java
dev-workflow-ui/webContent/view/login.xhtml

Send status code 401 if login fails
Enhance WebTestLogin to check that status code is 401 and not an AJAX request
Similar to https://github.com/axonivy/engine-cockpit/pull/1241

XIVY-16048 Send 401 status code if login fails

---

dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/ResponsibleModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDetailsIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/user/UserComponentIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/user/UserComponentModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/CaseUtil.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/TaskUtil.java
dev-workflow-ui/webContent/includes/components/caseDetails/taskList.xhtml
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/includes/components/userDetails/userdetail-usertasks.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml

Just getting rid of depreaction warnings. The UI
will need to improved afterwards in its own story.
Not a beau, but good enough for now:

XIVY-1259 Fix deprecation warnings

---

dev-workflow-ui/src/ch/ivyteam/workflowui/user/UserComponentModel.java

XIVY-15850 Back to old behavior if member is unknown

---

dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml

XIVY-15851 Multiple task responsibles

---

dev-workflow-ui/webContent/view/tasks.xhtml

Fix responsible tooltip styles

---

dev-workflow-ui-test-data/processes/EngineMode.p.json
dev-workflow-ui-test-data/processes/GenerateTask.p.json
dev-workflow-ui-test-data/processes/NotEmbedInFrame.p.json
dev-workflow-ui-test-data/processes/TestCustomFieldValues.p.json
dev-workflow-ui-test-data/processes/TestData.p.json
dev-workflow-ui-test-data/processes/TestService.p.json
dev-workflow-ui-test-data/processes/TestViewPermission.p.json
dev-workflow-ui-test-data/processes/makeAdminUser.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/DummyHtmlDialog/DummyHtmlDialogProcess.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TaskTestDialog/TaskTestDialogProcess.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TestDefaultPage/TestDefaultPageProcess.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TestDialog1/TestDialog1Process.p.json
dev-workflow-ui-test-data/src_hd/ch/ivyteam/ivy/project/workflow/TestDialog2/TestDialog2Process.p.json
dev-workflow-ui/processes/Main.p.json
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/ResponsibleModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/TaskUtil.java

- **XIVY-16581 Convert processes**
- **XIVY-16581 Fix deprecation warnings**

XIVY-16581 Fix deprecation warnings

---

dev-workflow-ui/webContent/resources/js/dom-select.js

- Do not stop selection mode on element click, only after escape or disable

XIVY-16156 Selection mode

---

dev-workflow-ui/webContent/resources/js/preview-ws.js

https://github.com/axonivy/dev-workflow-ui/pull/625

Refresh dialog when enable autorefresh > R13.1

---

dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/starts.xhtml
dev-workflow-ui/webContent/view/switch-user.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml
dev-workflow-ui/webContent/view/webservices.xhtml

found a few instances of a unused css class in html elements

Cleanup unused css classes in html

---

dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CaseModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/intermediateEvents/IntermediateEventDetailsBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/intermediateEvents/IntermediateEventElementModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/intermediateEvents/IntermediateEventElementsBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/intermediateEvents/IntermediateEventInstance.java
dev-workflow-ui/src/ch/ivyteam/workflowui/intermediateEvents/IntermediateEventInstanceLazyDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/notification/NotificationDto.java
dev-workflow-ui/src/ch/ivyteam/workflowui/signals/BoundarySignalReceiverModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/signals/BoundarySignalsModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/signals/SignalEventModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/signals/SignalsBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/signals/SignalsModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TaskModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/intermediate-event.xhtml
dev-workflow-ui/webContent/view/intermediate-events.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml

Primefaces models used in `LazyDataModel<T>` need to have no-args constuctor `public MyClass() {}` or they fail in some instances:

Fix models used for primefaces LazyDataModel

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/ProcessesBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/ProjectFilterModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/SessionFilters.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/StartsDataModel.java
dev-workflow-ui/webContent/view/starts.xhtml

Project filters are persisted in `IAttributeStore`
They can be also passed in the URL parameter `?projects=dev-workflow-ui-test-data`
Search can also be passed by URL parameter `?q=TestData.ivp` but does not get persisted

XIVY-17184 Persistent filters

---

dev-workflow-ui-test-data/.classpath
dev-workflow-ui-test-data/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui-test-data/.settings/org.eclipse.wst.common.component
dev-workflow-ui-test/.classpath
dev-workflow-ui-test/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui-test/.settings/org.eclipse.wst.common.component
dev-workflow-ui-web-test/.classpath
dev-workflow-ui-web-test/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui-web-test/.settings/org.eclipse.wst.common.component
dev-workflow-ui/.classpath
dev-workflow-ui/.settings/ch.ivyteam.ivy.designer.prefs
dev-workflow-ui/.settings/org.eclipse.wst.common.component

manual re-run of the improved converter; to verify it in the field
https://github.com/axonivy/core/pull/9730

convert using improved src_generated converter

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCasesIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCleanup.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDefaultPagesIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProcessViewerIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProcessViewerPermissionIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/casemap/CaseMapModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/login/SwitchUserBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/webservices/WebServicesBean.java
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/starts.xhtml
dev-workflow-ui/webContent/view/switch-user.xhtml
dev-workflow-ui/webContent/view/tasks.xhtml
dev-workflow-ui/webContent/view/webservices.xhtml

Slightly "hacky" workaround
Proper solution would require PrimeFaces 15

Do not overwrite search input on long processing filtering

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProfileIT.java
dev-workflow-ui/cms/cms_de.yaml
dev-workflow-ui/cms/cms_en.yaml
dev-workflow-ui/src/ch/ivyteam/workflowui/profile/NotificationChannelDataModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/profile/ProfileBean.java
dev-workflow-ui/webContent/resources/css/workflow-ui.css
dev-workflow-ui/webContent/view/profile.xhtml

Always thought this page was a bit overwhelming so I simplified it a bit while waiting on commons-lang builds
Before:
After:

Improve profile page

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProfileIT.java

Group and stabilize WebTestProfile > R12

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestProfileIT.java

Group and stabilize WebTestProfile > R10

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseDetailsIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCasesIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CaseModel.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesDetailsIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/cases/CasesIvyDevWfBean.java
dev-workflow-ui/src/ch/ivyteam/workflowui/util/CaseUtil.java
dev-workflow-ui/webContent/view/case.xhtml
dev-workflow-ui/webContent/view/cases.xhtml
dev-workflow-ui/webContent/view/home.xhtml

Fix test assertions > R12

---

dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
dev-workflow-ui/src/ch/ivyteam/workflowui/starts/StartsDataModel.java
dev-workflow-ui/webContent/view/starts.xhtml

seems like accidentally introduced a small bug while working on project filters. added new tests.
also will merge to 12.0

XIVY-17419 Fix starts table sorting
