axonivy/dev-workflow-ui

- dev-workflow-ui/webContent/view/frame.xhtml
- Replace the browser history with the current dialog url, so a refresh loads the dialog url in the iframe instead of restart the process
**Before:**
**After:**
> XIVY-9722 Refresh iframe only refreshes the dialog and not the process

- dev-workflow-ui/webContent/includes/components/startsPanel.xhtml
Sometimes i wish i could see what application a PMV belongs to. I think this solution makes it really unintrusive but still useful
> Add application name tooltip on starts page PMV hover

- dev-workflow-ui/src/ch/ivyteam/workflowui/user/UserComponentModel.java
Same as on master: https://github.com/axonivy/dev-workflow-ui/pull/197
> XIVY-11209 Task responsible show display name instead of abbreviation > R10

- dev-workflow-ui/src/ch/ivyteam/workflowui/user/UserComponentModel.java
> XIVY-11209 Task responsible show display name instead of abbreviation

- dev-workflow-ui-web-test/pom.xml
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebDocuScreenshots.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCaseMapIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCleanup.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomeRedirect.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestIntermediateEventsIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestSignalsIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/util/WorkflowUiUtil.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginIvyDevWfBean.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/login/LoginUtil.java
- dev-workflow-ui/webContent/includes/template/template.xhtml
The problem is not that the case/task id is not on the parameter, the problem is that if you do a redirect to the login page, then a POST request is first triggered (without any query params). The original URL is then evaluated from this POST request instead of the inital page request.
> XIVY-11246 Fix npe after user switch if orignal url is case/task detail

- Jenkinsfile
- maven/deploy/pom.xml
- Own stage for deploy to engine
- Do not fail build if deployment to engine fails (only stage fails)
- Make deployToEngineUrl configurable
- Show demo link only if deployment works
- Demo link is now always correct (application name truncated)
> Improve deploy to engine (11.1)

- Jenkinsfile
- maven/deploy/pom.xml
- Own stage for deploy to engine
- Do not fail build if deployment to engine fails (only stage fails)
- Make deployToEngineUrl configurable
- Show demo link only if deployment works
- Demo link is now always correct (application name truncated)
> Improve deploy to engine

- Jenkinsfile
- maven/deploy/pom.xml
- Own stage for deploy to engine
- Do not fail build if deployment to engine fails (only stage fails)
- Make deployToEngineUrl configurable
- Show demo link only if deployment works
- Demo link is now always correct (application name truncated)
> Improve deploy to engine (10.0)

- dev-workflow-ui/webContent/view/frame.xhtml
> Proposal: Change frame view -> move the title to the frame card

- dev-workflow-ui/webContent/view/frame.xhtml
this fix was already there, see https://github.com/axonivy/dev-workflow-ui/pull/149/files
fix does not work for safari...
> XIVY-13226 fix flickering when frame content gets unloaded

- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestNotification.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/notification/NotificationActionDTO.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/notification/NotificationDto.java
- dev-workflow-ui/webContent/includes/template/notifications.xhtml
- dev-workflow-ui/webContent/resources/css/workflow-ui.css
Before:
After:
I noticed some issues we probably should discuss. Probably easier to explain in a meeting, but here are some notes:
Even though `WebNotification` contains a `List<WebNotificationAction>`, I assume there is exactly one `WebNotificationType.INFO` and zero or one `WebNotificationType.RUN` for now. If this changes, the implementation of the UI has to change as well. If this stays, maybe we should just provide two individual attributes for these?
In case of a list (at least for `WebNotificationType.RUN`) we could iterate over all of them and display a link/icon for each. However, I do not know what they do. All would have the same icon and the same tool tip. Another attribute like a description would be necessary for customization. To also make this language specific seems …
> XIVY-13150 implement notification actions

- dev-workflow-ui-test-data/webContent/layouts/includes/progress-loader.xhtml
- dev-workflow-ui/webContent/includes/components/allTasksTable.xhtml
- dev-workflow-ui/webContent/includes/components/caseDetails/caseList.xhtml
- dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
- dev-workflow-ui/webContent/includes/components/caseDetails/taskList.xhtml
- dev-workflow-ui/webContent/includes/components/casesTable.xhtml
- dev-workflow-ui/webContent/includes/components/personalTasksTable.xhtml
- dev-workflow-ui/webContent/includes/components/signals/boundarySignals.xhtml
- dev-workflow-ui/webContent/includes/components/signals/firedSignals.xhtml
- dev-workflow-ui/webContent/includes/components/startsPanel.xhtml
- dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
- dev-workflow-ui/webContent/includes/components/taskDetails/descriptionCardHeaderActions.xhtml
- dev-workflow-ui/webContent/includes/template/progress-loader.xhtml
- dev-workflow-ui/webContent/includes/template/sidebar.xhtml
- dev-workflow-ui/webContent/includes/template/template.xhtml
- dev-workflow-ui/webContent/resources/components/workflowEventsTable.xhtml
- dev-workflow-ui/webContent/view/case.xhtml
- dev-workflow-ui/webContent/view/home.xhtml
- dev-workflow-ui/webContent/view/intermediateEventDetails.xhtml
- dev-workflow-ui/webContent/view/login.xhtml
- dev-workflow-ui/webContent/view/starts.xhtml
- dev-workflow-ui/webContent/view/task.xhtml
Replace old JSF namespaces http://java.sun.com/jsf/* with new JSF 2.2 namepaces http://xmlns.jcp.org/jsf/*
> XIVY-13553 Streamline jsf namespaces from sun.com/jsf to jcp.org/jsf

- .editorconfig
- a double-whitespace at the end of a line in markdown is the valid way to express a line-break ... therefore we should not prevent this with our editor config
> fix: code-of-conduct by not applying code whitespace rules to markdown

- dev-workflow-ui/webContent/includes/template/exception-details.xhtml
- dev-workflow-ui/webContent/includes/template/exception.xhtml
- dev-workflow-ui/webContent/includes/template/template.xhtml
Wondering that we don't have an ajax exception handler here? But maybe there is a specific reason? Copied the one from engine cockpit...
```
Could not handle exception!
java.lang.IllegalArgumentException: No default error page (Status 500 or java.lang.Throwable) and no error page for type "class javax.faces.application.ViewExpiredException" defined!
at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.evaluateErrorPage(PrimeExceptionHandler.java:441)
at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.handleRedirect(PrimeExceptionHandler.java:377)
at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.handleAjaxException(PrimeExceptionHandler.java:224)
at org.primefaces.application.exceptionhandler.PrimeExceptionHandler.handle(PrimeExceptionHa …
```
> Add ajax exception handler

- maven/config/pom.xml
Maven 3.9.8 already tries to use maven 4 plugins. Because they are not compatible it will give a warning and is using an older one.
> Fix version of maven plugins (best practices and warning with Maven 4

- dev-workflow-ui/webContent/includes/template/template.xhtml
I noticed that the cog icon looked kind of out of place. I checked and it is a streamline icon `si si-...` while the other surrounding icons are primeicons `pi pi-...`
Also i didnt notice `animated` and `swing` classes affect anything.
> Streamline cockpit icon to use the same family as surrounding icons

- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestTasksIT.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/DateTimeIvyDevWfBean.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/util/DateUtil.java
- dev-workflow-ui/webContent/includes/components/caseDetails/description.xhtml
- dev-workflow-ui/webContent/includes/components/casesTable.xhtml
- dev-workflow-ui/webContent/includes/components/personalTasksTable.xhtml
- dev-workflow-ui/webContent/includes/components/signals/firedSignals.xhtml
- dev-workflow-ui/webContent/includes/components/taskDetails/description.xhtml
- dev-workflow-ui/webContent/includes/components/tasksTable.xhtml
- dev-workflow-ui/webContent/resources/components/time.xhtml
- dev-workflow-ui/webContent/view/home.xhtml
- dev-workflow-ui/webContent/view/notesDialog.xhtml
- renamed "datetime" component to "time" (because it shows prettytime and datetime on hover)
- new "datetime" component which shows datetime and on hover prettytime
- those components are now used on case and task details pages
- streamline "N/A" string behaviour by removing it
> XIVY-14658 Streamline datetime component and occurences

- dev-workflow-ui/webContent/resources/css/workflow-ui.css
> XIVY-14658 Less padding on tables

- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestCleanup.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestDefaultPagesIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomeRedirect.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestHomepageIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestIntermediateEventsIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestLoginIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestSignalsIT.java
- dev-workflow-ui-web-test/src_test/ch/ivyteam/ivy/project/workflow/webtest/WebTestStartsIT.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/SidebarIvyDevWfBean.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDataModel.java
- dev-workflow-ui/webContent/includes/template/sidebar.xhtml
- dev-workflow-ui/webContent/resources/css/workflow-ui.css
- Add our own css class for topbar navigation styling (primefaces likes to disappear on hover?)
- Start processes using start button instead by row click (less flaky)
- Move a bit of the sidebar navigation code to java bean
- Adjust TaskDataModel to only filter system tasks for the admin
> Reduce WebTest flakiness

- dev-workflow-ui-test-data/cms/cms_de.yaml
- dev-workflow-ui-test-data/cms/cms_en.yaml
- dev-workflow-ui-test-data/config/custom-fields.yaml
- dev-workflow-ui-test-data/dataclasses/ch/ivyteam/ivy/project/workflow/TestCustomFieldValuesData.d.json
- dev-workflow-ui-test-data/processes/TestCustomFieldValues.p.json
- dev-workflow-ui-test/src_test/ch/ivyteam/ivy/project/workflow/test/TestCustomFieldModel.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/customfield/CustomFieldModel.java
- dev-workflow-ui/webContent/resources/components/customFields.xhtml
- Use the new API for translated custom field values
- Add tooltip to custom field value that shows label and value
- Add new test process that has configured multi language values for custom fields
- Add tests for CustomFieldModel
> Feature/XIVY-15825 Custom field values

- dev-workflow-ui/src/ch/ivyteam/workflowui/FrameIvyDevWfBean.java
- dev-workflow-ui/src/ch/ivyteam/workflowui/casemap/SidestepUtil.java
- dev-workflow-ui/webContent/includes/template/template.xhtml
- dev-workflow-ui/webContent/resources/js/dom-select.js
- dev-workflow-ui/webContent/resources/js/frame.js
- dev-workflow-ui/webContent/resources/js/preview-ws.js
- dev-workflow-ui/webContent/view/frame.xhtml
cherry-pick: #580
- WebSocket to backend
- Element picker for navigation
- AutoRefresh if dialog changes
cherry-pick: https://github.com/axonivy/dev-workflow-ui/pull/584
- Add id to selection overlay
cherry-pick: https://github.com/axonivy/dev-workflow-ui/pull/588
- Do not spin autorefresh icon
> XIVY-16477 Preview > R12

- dev-workflow-ui/src/ch/ivyteam/workflowui/tasks/TasksDetailsBean.java
If a POST ajax request is happening on the task detail page, and after that the task is directly started, the originUrl will be evaluated based on this POST request. The problem here is that this request does not include the query parameters, so the task id is no longer there and therefore there is no selected task.
> XIVY-16798 Fix NPE on task redirect
